build.sh
kokoro/gcp_ubuntu/kokoro_build.sh

TESTED:
Running Kokoro on this PR

Fix script to let Kokoro run

---

README.md

This is the build status of the main branch and is run each time a PR is merged

Update README.md to include Build Status

---

e2e-test/clients.py
e2e-test/e2e.py
e2e-test/e2e.sh
pom.xml
server/pom.xml

Ran the [merge_all_dependabot_PRs.sh](https://github.com/google/fhir-data-pipes/blob/master/utils/merge_all_dependabot_PRs.sh) to merge all dependabot PRs into one, then reverted spring-boot version update to be Java 11 compatible.
TESTED:
Relied on the continuous build

Merges dependabot PRs into one

---

Dockerfile
README.md
exec/pom.xml
exec/src/main/java/com/google/fhir/proxy/MainApp.java
exec/src/test/java/com/google/fhir/proxy/MainAppTest.java
plugins/pom.xml
pom.xml
server/pom.xml
server/src/main/java/com/google/fhir/proxy/FhirProxyServer.java

This is the first step to release library artifacts that can easily be used in other projects (see #40).
TESTED:
Ran the server locally and verified that I can fetch resources with a valid access-token.

Separates main into its own module

---

exec/pom.xml
pom.xml
server/pom.xml

We currently cannot run dependabot PRs through our Kokoro based CI. Used [merge_all_dependabot_PRs.sh](https://github.com/google/fhir-data-pipes/blob/master/utils/merge_all_dependabot_PRs.sh) to merge all currently pending such PRs into a PR of my own.
TESTED:
Relying on unit/e2e tests only.
**NOTE**: This has multiple commits because it merges those of depdendabot.

Merging all recent dependabot PRs

---

plugins/src/main/java/com/google/fhir/proxy/plugin/AccessGrantedAndUpdateList.java
plugins/src/main/java/com/google/fhir/proxy/plugin/ListAccessChecker.java
server/src/main/java/com/google/fhir/proxy/BearerAuthorizationInterceptor.java
server/src/main/java/com/google/fhir/proxy/HttpFhirClient.java
server/src/main/java/com/google/fhir/proxy/PatientFinderImp.java
server/src/main/java/com/google/fhir/proxy/interfaces/AccessChecker.java
server/src/main/java/com/google/fhir/proxy/interfaces/AccessCheckerFactory.java
server/src/main/java/com/google/fhir/proxy/interfaces/AccessDecision.java
server/src/test/java/com/google/fhir/proxy/HttpFhirClientTest.java

Transferred some of the internal issues to GitHub ones and added more javadoc for interfaces.
TESTED:
NA; documentation changes only.

Added more javadoc and GitHub issues

---

plugins/src/main/java/com/google/fhir/gateway/plugin/PatientAccessChecker.java
plugins/src/test/java/com/google/fhir/gateway/plugin/PatientAccessCheckerTest.java

Added support for conditional delete in Patient access checker
Issue https://github.com/google/fhir-access-proxy/issues/43
TESTED: Verified the delete workflows locally for a patient and observations for patient the access token scope.

Allow conditional delete in Patient access checker

---

plugins/src/main/java/com/google/fhir/gateway/plugin/ListAccessChecker.java
plugins/src/test/java/com/google/fhir/gateway/plugin/ListAccessCheckerTest.java
pom.xml

Added support for conditional delete in List access checker
Issue https://github.com/google/fhir-access-proxy/issues/43
TESTED: Verified the delete workflows locally for a patient and observations for patients in the access list.

Allow conditional delete in List access checker

---

kokoro/gcp_ubuntu/continuous.cfg
kokoro/gcp_ubuntu/kokoro_build.sh
kokoro/gcp_ubuntu/presubmit.cfg

Our continuous-build has been broken since we renamed the repo earlier this week. I am trying to update Kokoro config to fix it.
TESTED:
I am not sure if I can test these config changes before submitting it. There is another required update on the internal Kokoro config side which is needed as well.

Changes access-proxy to gateway for Kokoro

---

plugins/src/main/java/com/google/fhir/gateway/plugin/PatientAccessChecker.java
plugins/src/test/java/com/google/fhir/gateway/plugin/AccessCheckerTestBase.java
plugins/src/test/java/com/google/fhir/gateway/plugin/ListAccessCheckerTest.java
plugins/src/test/java/com/google/fhir/gateway/plugin/PatientAccessCheckerTest.java
plugins/src/test/resources/bundle_transaction_delete_non_patient.json
plugins/src/test/resources/bundle_transaction_delete_patient.json
plugins/src/test/resources/bundle_transaction_delete_patient_unauthorized.json
server/src/main/java/com/google/fhir/gateway/BundlePatients.java
server/src/main/java/com/google/fhir/gateway/PatientFinderImp.java

Support delete operations using FHIR bundle in List and Patient access checkers
Issue https://github.com/google/fhir-access-proxy/issues/43
TESTED: Verified the delete workflows locally for Delete observations in a FHIR Bundle for list access checker.

Delete support in FHIR Bundle

---

Dockerfile
doc/design.md
exec/pom.xml
plugins/pom.xml
pom.xml
server/pom.xml

These are required changes in POM files to be able to deploy on Maven. The release process is documented [here](https://docs.google.com/document/d/1snWVINGkSyz0-xIMJm9vnDRygPimQCmwK9v_4_ygOPs/edit?resourcekey=0-Yqn8DKuV7SY94bISO-65vA).
Fixes #40 
This also has some formatting changes to `doc/design.md` file which have are automatically done during `mvn package`; these have been missed from the original commit of this file.
TESTED:
Ran the following:
```
mvn clean deploy -Psonatype-oss-release
```
and checked that the release appeared [here](https://repo.maven.apache.org/maven2/com/google/fhir/gateway/). Then built the `exec` module (not from root) by pulling the released resources.
Relied on e2e/unit tests.
No? Please take some time and review …

POM related changes for deploy

---

plugins/src/main/java/com/google/fhir/gateway/plugin/ListAccessChecker.java
plugins/src/main/java/com/google/fhir/gateway/plugin/PatientAccessChecker.java
server/src/main/java/com/google/fhir/gateway/FhirUtil.java
server/src/main/java/com/google/fhir/gateway/PatientFinderImp.java
server/src/main/java/com/google/fhir/gateway/interfaces/PatientFinder.java
server/src/test/java/com/google/fhir/gateway/FhirUtilTest.java

https://github.com/google/fhir-gateway/issues/104
Refactored `PatientFinder` 's method `findPatientsInBundle` to directly take `Bundle` as an argument
Refactored PatientAccessChecker to remove the duplicate creation of a bundle from the request body
TESTED:
Made sure that all the existing use cases still work post refactoring.

Remove duplicate creation of bundle from request details

---

pom.xml
server/src/main/java/com/google/fhir/gateway/interfaces/AccessDecision.java

This is a minor change which fixes a compilation error with JDK 17.
TESTED:
Relying on unit/e2e test.

google-java-format update

---

Dockerfile
exec/pom.xml
plugins/pom.xml
pom.xml
server/pom.xml

Updated versions for a new maven release. The first commit is automatically created using:
```
mvn versions:set -DnewVersion=0.2.0
```
and the second commit is the corresponding Dockerfile changes.
TESTED:
Relying on unit/e2e tests.

updated version to 0.2.0

---

Dockerfile
exec/pom.xml
plugins/pom.xml
pom.xml
server/pom.xml

This was automatically created by 
```
mvn versions:set -DnewVersion=0.2.1-SNAPSHOT
```
For the rationale of having SNAPSHOT versions see [here](https://central.sonatype.org/publish/publish-maven/#performing-a-snapshot-deployment) and [here](https://stackoverflow.com/questions/5901378).
TESTED:
Relying on unit/e2e tests.

Version change for the next dev cycle

---

exec/pom.xml
plugins/pom.xml
pom.xml
server/pom.xml

This is auto-generated by:
```bash
mvn versions:set -DnewVersion=0.3.1
```
TESTED:
This includes some minor changes compared to the release we made a few days ago; so just relied on presubmit checks.

Preparing version 0.3.1 release

---

exec/pom.xml
plugins/pom.xml
pom.xml
server/pom.xml

This is automatically generated by running `mvn versions:set -DnewVersion=0.3.2`.
TESTED:
Relying on unit/e2e tests as not much changes has gone into this since last release.

Preparing for release 0.3.2

---

.github/workflows/codecov.yml
Dockerfile
README.md
coverage/pom.xml
doc/design.md
pom.xml

This is to enable Codecov on the repo plus some minor lint issues that were fixed by `mvn package`.
TESTED:
Relied on e2e/unit tests.

added codecov and minor lints

---

Dockerfile
coverage/pom.xml
exec/pom.xml
plugins/pom.xml
pom.xml
server/pom.xml
server/src/main/java/com/google/fhir/gateway/BearerAuthorizationInterceptor.java
server/src/main/java/com/google/fhir/gateway/interfaces/RequestMutation.java
server/src/test/java/com/google/fhir/gateway/BearerAuthorizationInterceptorTest.java

Closes #294 which Adds support for removing query params in request mutations
TESTED:
Please replace this with a description of how you tested your PR beyond the
automated e2e/unit tests.

Add support for removing query params in request mutations

---

.github/workflows/codecov.yml
.github/workflows/codeql.yml
Dockerfile
exec/pom.xml
exec/src/main/java/com/google/fhir/gateway/CustomFhirEndpointExample.java
exec/src/main/java/com/google/fhir/gateway/CustomGenericEndpointExample.java
exec/src/test/java/com/google/fhir/gateway/MainAppTest.java
plugins/pom.xml
plugins/src/main/java/com/google/fhir/gateway/plugin/PatientAccessChecker.java
pom.xml
server/pom.xml
server/src/main/java/com/google/fhir/gateway/BearerAuthorizationInterceptor.java
server/src/main/java/com/google/fhir/gateway/FhirProxyServer.java
server/src/main/java/com/google/fhir/gateway/interfaces/PatientFinder.java
server/src/test/java/com/google/fhir/gateway/BearerAuthorizationInterceptorTest.java

Fixes #155; in particular see [this comment](https://github.com/google/fhir-gateway/issues/155#issuecomment-2098939365) for more details. The main motivation was to upgrade the Spring version to address vulnerabilities but it also enabled us to upgrade HAPI and some other library versions.
TESTED:
Ran the gateway locally and tested both `list` and `patient` access-checker with a local Keycloak.

Updates Spring to 6.1.13 and other version updates

---

coverage/pom.xml
exec/pom.xml
plugins/pom.xml
pom.xml
server/pom.xml

Automatically created by running:
```
mvn versions:set -DnewVersion=0.4.1-SNAPSHOT
```
TESTED:
Please replace this with a description of how you tested your PR beyond the
automated e2e/unit tests.

Version upgrade for the next dev iteration

---

plugins/src/main/java/com/google/fhir/gateway/plugin/ListAccessChecker.java
plugins/src/main/java/com/google/fhir/gateway/plugin/PatientAccessChecker.java
pom.xml

Running Spotless with JDK 21 requires google-java-format of at least 1.17.0 . This PR upgrades it to the latest release version 1.27.0
**This PR  :**
- Upgrades Google Java Format dependency version to latest version `1.27.0`
- Runs spotless apply which reformats the files breaking the new rules
TESTED:
Please replace this with a description of how you tested your PR beyond the
automated e2e/unit tests.

Upgrades Google Java Format dependency version

---

exec/src/main/java/com/google/fhir/gateway/MainApp.java
plugins/src/main/java/com/google/fhir/gateway/plugin/ListAccessChecker.java
plugins/src/main/java/com/google/fhir/gateway/plugin/PatientAccessChecker.java
server/src/main/java/com/google/fhir/gateway/AuditEventBuilder.java
server/src/main/java/com/google/fhir/gateway/AuditEventHelperImpl.java
server/src/main/java/com/google/fhir/gateway/BearerAuthorizationInterceptor.java
server/src/main/java/com/google/fhir/gateway/FhirProxyServer.java
server/src/main/java/com/google/fhir/gateway/FhirUtil.java
server/src/main/java/com/google/fhir/gateway/HttpFhirClient.java
server/src/main/java/com/google/fhir/gateway/JwtUtil.java
server/src/main/java/com/google/fhir/gateway/PatientFinderImp.java
server/src/main/java/com/google/fhir/gateway/ProxyConstants.java
server/src/main/java/com/google/fhir/gateway/RequestDetailsToReader.java
server/src/main/java/com/google/fhir/gateway/TokenVerifier.java
server/src/main/java/com/google/fhir/gateway/interfaces/AccessDecision.java
server/src/main/java/com/google/fhir/gateway/interfaces/AuditEventHelper.java
server/src/main/java/com/google/fhir/gateway/interfaces/PatientFinder.java
server/src/main/java/com/google/fhir/gateway/interfaces/RequestDetailsReader.java
server/src/test/java/com/google/fhir/gateway/BearerAuthorizationInterceptorTest.java
server/src/test/java/com/google/fhir/gateway/TestUtil.java

Runs maven clean package for out of date/sync files.
N/A
TESTED:
N/A

Maven clean package
